export const typeNames = {
  grass: "green",
  poison: "purple",
  fire: "red",
  flying: "LightBlue",
  water: "MediumSlateBlue",
  bug: "Olive",
  rock: "#DAA520",
  ground: "#B8860B",
  psychic: "DarkOrchid",
  electric: "#FFD700",
  steel: "LightSteelBlue",
  ice: "LightSkyBlue",
  ghost: "MediumPurple",
  fairy: "Pink",
  dragon: "Maroon",
  dark: "black",
  fighting: "Tan",
  normal: "grey",
};
